-- Capstone NHANES pipeline
-- Step 2: create raw tables for CSV imports

-- this communicates that all tables in the script belong in the raw schema
SET search_path TO raw;

-- c1 demo table set up
DROP TABLE IF EXISTS raw.c1_demo;

CREATE TABLE raw.c1_demo (
    SEQN TEXT,
    SDDSRVYR TEXT,
    RIDSTATR TEXT,
    RIDEXMON TEXT,
    RIAGENDR TEXT,
    RIDAGEYR TEXT,
    RIDAGEMN TEXT,
    RIDAGEEX TEXT,
    RIDRETH1 TEXT,
    RIDRETH2 TEXT,
    DMQMILIT TEXT,
    DMDBORN TEXT,
    DMDCITZN TEXT,
    DMDYRSUS TEXT,
    DMDEDUC3 TEXT,
    DMDEDUC2 TEXT,
    DMDEDUC TEXT,
    DMDSCHOL TEXT,
    DMDMARTL TEXT,
    DMDHHSIZ TEXT,
    INDFHINC TEXT,
    INDFMINC TEXT,
    INDFMPIR TEXT,
    RIDEXPRG TEXT,
    RIDPREG TEXT,
    DMDHRGND TEXT,
    DMDHRAGE TEXT,
    DMDHRBRN TEXT,
    DMDHREDU TEXT,
    DMDHRMAR TEXT,
    DMDHSEDU TEXT,
    WTINT2YR TEXT,
    WTINT4YR TEXT,
    WTMEC2YR TEXT,
    WTMEC4YR TEXT,
    SDMVPSU TEXT,
    SDMVSTRA TEXT
);

-- c1_alt_ast_ggt_glucose table set up
DROP TABLE IF EXISTS raw.c1_alt_ast_ggt_glucose;

CREATE TABLE raw.c1_alt_ast_ggt_glucose (
  SEQN TEXT,
  LBXSAL TEXT,
  LBDSALSI TEXT,
  LBXSATSI TEXT,
  LBXSASSI TEXT,
  LBDSAPSI TEXT,
  LBXSBU TEXT,
  LBDSBUSI TEXT,
  LBXSCA TEXT,
  LBDSCASI TEXT,
  LBXSCH TEXT,
  LBDSCHSI TEXT,
  LBXSCS3SI TEXT,
  LBXSGTSI TEXT,
  LBXSGL TEXT,
  LBDSGLSI TEXT,
  LBXSIR TEXT,
  LBDSIRSI TEXT,
  LBDSLDSI TEXT,
  LBDSPH TEXT,
  LBDSPHSI TEXT,
  LBDSTB TEXT,
  LBDSTBSI TEXT,
  LBXSTP TEXT,
  LBDSTPSI TEXT,
  LBXSTR TEXT,
  LBDSTRSI TEXT,
  LBXSUA TEXT,
  LBDSUASI TEXT,
  LBDSCR TEXT,
  LBDSCRSI TEXT,
  LBXSNASI TEXT,
  LBXSKSI TEXT,
  LBXSCLSI TEXT,
  LBXSOSSI TEXT,
  LBXSGB TEXT,
  LBDSGBSI TEXT,
  LBXFSH TEXT,
  LBDFSHSI TEXT,
  LBXLH TEXT,
  LBDLHSI TEXT
);
-- c1_bmi table set up
DROP TABLE IF EXISTS raw.c1_bmi;

CREATE TABLE raw.c1_bmi (
  SEQN TEXT,
  BMXWT TEXT,
  BMIWT TEXT,
  BMXRECUM TEXT,
  BMIRECUM TEXT,
  BMXHEAD TEXT,
  BMIHEAD TEXT,
  BMXHT TEXT,
  BMIHT TEXT,
  BMXBMI TEXT,
  BMXLEG TEXT,
  BMILEG TEXT,
  BMXCALF TEXT,
  BMICALF TEXT,
  BMXARML TEXT,
  BMIARML TEXT,
  BMXARMC TEXT,
  BMIARMC TEXT,
  BMXWAIST TEXT,
  BMIWAIST TEXT,
  BMXTHICR TEXT,
  BMITHICR TEXT,
  BMXTRI TEXT,
  BMITRI TEXT,
  BMXSUB TEXT,
  BMISUB TEXT
);

-- c1 crp table set up
DROP TABLE IF EXISTS raw.c1_crp;

CREATE TABLE raw.c1_crp (
  SEQN TEXT,
  LBXCRP TEXT,
  LBXFB TEXT,
  LBDFBSI TEXT,
  LBDBAP TEXT,
  URDNT TEXT
);

-- c1 diabetes table set up
--need this line if doesnt work on first try 
DROP TABLE IF EXISTS raw.c1_diabetes;

CREATE TABLE raw.c1_diabetes (
  SEQN TEXT,
  DIQ010 TEXT,
  DID040G TEXT,
  DID040Q TEXT,
  DIQ050 TEXT,
  DID060G TEXT,
  DID060Q TEXT,
  DIQ060U TEXT,
  DIQ070 TEXT,
  DIQ080 TEXT,
  DIQ090 TEXT,
  DIQ100 TEXT,
  DIQ110 TEXT,
  DIQ120 TEXT,
  DIQ130 TEXT,
  DIQ140 TEXT,
  DIQ150 TEXT
);



-- c1 folate, b12, hcy, mma and iron table set up

DROP TABLE IF EXISTS raw.c1_folate_b12_hcy_mma_iron;

CREATE TABLE raw.c1_folate_b12_hcy_mma_iron (
  SEQN TEXT,
  LB2BCD TEXT,
  LB2BCDSI TEXT,
  LB2BPB TEXT,
  LB2BPBSI TEXT,
  LB2RBF TEXT,
  LB2RBFSI TEXT,
  LB2THG TEXT,
  LB2THGSI TEXT,
  LB2HCY TEXT,
  LB2FER TEXT,
  LB2FERSI TEXT,
  LB2B12 TEXT,
  LB2B12SI TEXT,
  LB2FOL TEXT,
  LB2FOLSI TEXT,
  LB2MMA TEXT,
  LB2COT TEXT,
  LB2COTLC TEXT
);