-- Capstone NHANES pipeline
-- Step 2: create raw tables for CSV imports

-- this communicates that all tables in the script belong in the raw schema
SET search_path TO raw;

-- c2 c2_alt_ast_ggt_glucose table set up
DROP TABLE IF EXISTS raw.c2_alt_ast_ggt_glucose;

CREATE TABLE raw.c2_alt_ast_ggt_glucose (
    SEQN TEXT,
    LBXSAL TEXT,
    LBDSALSI TEXT,
    LBXSATSI TEXT,
    LBXSASSI TEXT,
    LBXSAPSI TEXT,
    LBXSBU TEXT,
    LBDSBUSI TEXT,
    LBXSCA TEXT,
    LBDSCASI TEXT,
    LBXSCH TEXT,
    LBDSCHSI TEXT,
    LBXSC3SI TEXT,
    LBXSGTSI TEXT,
    LBXSGL TEXT,
    LBDSGLSI TEXT,
    LBXSIR TEXT,
    LBDSIRSI TEXT,
    LBXSLDSI TEXT,
    LBXSPH TEXT,
    LBDSPHSI TEXT,
    LBXSTB TEXT,
    LBDSTBSI TEXT,
    LBXSTP TEXT,
    LBDSTPSI TEXT,
    LBXSTR TEXT,
    LBDSTRSI TEXT,
    LBXSUA TEXT,
    LBDSUASI TEXT,
    LBXSCR TEXT,
    LBDSCRSI TEXT,
    LBXSNASI TEXT,
    LBXSKSI TEXT,
    LBXSCLSI TEXT,
    LBXSOSSI TEXT,
    LBXSGB TEXT,
    LBDSGBSI TEXT
);

-- c2_bmi table set up
DROP TABLE IF EXISTS raw.c2_bmi;

CREATE TABLE raw.c2_bmi (
  SEQN TEXT,
  BMDSTATS TEXT,
  BMDRECUF TEXT,
  BMDSUBF TEXT, 
  BMDTHICF TEXT,
  BMDLEGF TEXT,
  BMDARMLF TEXT,
  BMDCALFF TEXT,
  BMXWT TEXT,
  BMIWT TEXT,
  BMXRECUM TEXT,
  BMIRECUM TEXT,
  BMXHEAD TEXT,
  BMIHEAD TEXT,
  BMXHT TEXT,
  BMIHT TEXT,
  BMXBMI TEXT,
  BMXLEG TEXT,
  BMILEG TEXT,
  BMXCALF TEXT,
  BMICALF TEXT,
  BMXARML TEXT,
  BMIARML TEXT,
  BMXARMC TEXT,
  BMIARMC TEXT,
  BMXWAIST TEXT,
  BMIWAIST TEXT,
  BMXTHICR TEXT,
  BMITHICR TEXT,
  BMXTRI TEXT,
  BMITRI TEXT,
  BMXSUB TEXT,
  BMISUB TEXT 
);


-- c2_crp table set up
DROP TABLE IF EXISTS raw.c2_crp;

CREATE TABLE raw.c2_crp (
  SEQN TEXT,
  LBXCRP TEXT,
  LBXBAP TEXT,
  LBXPT21 TEXT
);

-- c2 demo table set up
DROP TABLE IF EXISTS raw.c2_demo;

CREATE TABLE raw.c2_demo (
  SEQN TEXT,
  SDDSRVYR TEXT,
  RIDSTATR TEXT,
  RIDEXMON TEXT,
  RIAGENDR TEXT,
  RIDAGEYR TEXT,
  RIDAGEMN TEXT,
  RIDAGEEX TEXT,
  RIDRETH1 TEXT,
  RIDRETH2 TEXT,
  DMQMILIT TEXT,
  DMDBORN TEXT,
  DMDCITZN TEXT,
  DMDYRSUS TEXT,
  DMDEDUC3 TEXT,
  DMDEDUC2 TEXT,
  DMDEDUC TEXT,
  DMDSCHOL TEXT,
  DMDMARTL TEXT,
  DMDHHSIZ TEXT,
  DNDHHINC TEXT,
  INDFMINC TEXT,
  INDFMPIR TEXT,
  RIDEXPRG TEXT,
  DMDHRGND TEXT,
  DMDHRAGE TEXT,
  DMDHRBRN TEXT,
  DMDHREDU TEXT,
  DMDHRMAR TEXT,
  DMDHSEDU TEXT,
  SIALANG TEXT,
  SIAPROXY TEXT,
  SIAINTRP TEXT,
  FIALANG TEXT,
  FIAPROXY TEXT,
  FIAINTRP TEXT,
  MIALANG TEXT,
  MIAPROXY TEXT,
  MIAINTRP TEXT,
  AIALANG TEXT,
  WTINT2YR TEXT,
  WTMEC2YR TEXT,
  SDMVPSU TEXT,
  SDMVSTRA TEXT
);

-- c2 diabetes table set up
--need this line if doesnt work on first try 
DROP TABLE IF EXISTS raw.c2_diabetes;

CREATE TABLE raw.c2_diabetes (
  SEQN TEXT,
  DIQ010 TEXT,
  DID040G TEXT,
  DID040Q TEXT,
  DIQ050 TEXT,
  DID060G TEXT,
  DID060Q TEXT,
  DIQ060U TEXT,
  DIQ070 TEXT,
  DIQ080 TEXT,
  DIQ090 TEXT,
  DIQ100 TEXT,
  DIQ110 TEXT,
  DIQ120 TEXT,
  DIQ130 TEXT,
  DIQ140 TEXT,
  DIQ150 TEXT
);

-- c2 folate, b12,table set up

DROP TABLE IF EXISTS raw.c2_folate_b12;

CREATE TABLE raw.c2_folate_b12 (
  SEQN TEXT,
  LBXRBF TEXT,
  LBDRBFSI TEXT,
  LBXB12 TEXT,
  LBDB12SI TEXT,
  LBXFOL TEXT,
  LBDFOLSI TEXT
  
);

-- c2 hcy, mma table set up

DROP TABLE IF EXISTS raw.c2_hcy_mma;

CREATE TABLE raw.c2_hcy_mma (
  SEQN TEXT,
  LBXHCY TEXT,
  LBXMMA TEXT
);

-- c2 iron table set up

DROP TABLE IF EXISTS raw.c2_iron;

CREATE TABLE raw.c2_iron (
  SEQN TEXT,
  LBXTFR TEXT,
  LBDFER TEXT,
  LBDFERSI TEXT
);